#pragma once

// TODO: Define this in the premake script depending on the platform.
#define DRAY_USE_GLFW

// From glfw3.h
#ifdef DRAY_USE_GLFW
	#define DRAY_KEY_SPACE              32
	#define DRAY_KEY_APOSTROPHE         39 
	#define DRAY_KEY_COMMA              44 
	#define DRAY_KEY_MINUS              45 
	#define DRAY_KEY_PERIOD             46 
	#define DRAY_KEY_SLASH              47 
	#define DRAY_KEY_0                  48
	#define DRAY_KEY_1                  49
	#define DRAY_KEY_2                  50
	#define DRAY_KEY_3                  51
	#define DRAY_KEY_4                  52
	#define DRAY_KEY_5                  53
	#define DRAY_KEY_6                  54
	#define DRAY_KEY_7                  55
	#define DRAY_KEY_8                  56
	#define DRAY_KEY_9                  57
	#define DRAY_KEY_SEMICOLON          59 
	#define DRAY_KEY_EQUAL              61 
	#define DRAY_KEY_A                  65
	#define DRAY_KEY_B                  66
	#define DRAY_KEY_C                  67
	#define DRAY_KEY_D                  68
	#define DRAY_KEY_E                  69
	#define DRAY_KEY_F                  70
	#define DRAY_KEY_G                  71
	#define DRAY_KEY_H                  72
	#define DRAY_KEY_I                  73
	#define DRAY_KEY_J                  74
	#define DRAY_KEY_K                  75
	#define DRAY_KEY_L                  76
	#define DRAY_KEY_M                  77
	#define DRAY_KEY_N                  78
	#define DRAY_KEY_O                  79
	#define DRAY_KEY_P                  80
	#define DRAY_KEY_Q                  81
	#define DRAY_KEY_R                  82
	#define DRAY_KEY_S                  83
	#define DRAY_KEY_T                  84
	#define DRAY_KEY_U                  85
	#define DRAY_KEY_V                  86
	#define DRAY_KEY_W                  87
	#define DRAY_KEY_X                  88
	#define DRAY_KEY_Y                  89
	#define DRAY_KEY_Z                  90
	#define DRAY_KEY_LEFT_BRACKET       91 
	#define DRAY_KEY_BACKSLASH          92 
	#define DRAY_KEY_RIGHT_BRACKET      93 
	#define DRAY_KEY_GRAVE_ACCENT       96 
	#define DRAY_KEY_WORLD_1            161
	#define DRAY_KEY_WORLD_2            162
	#define DRAY_KEY_ESCAPE             256
	#define DRAY_KEY_ENTER              257
	#define DRAY_KEY_TAB                258
	#define DRAY_KEY_BACKSPACE          259
	#define DRAY_KEY_INSERT             260
	#define DRAY_KEY_DELETE             261
	#define DRAY_KEY_RIGHT              262
	#define DRAY_KEY_LEFT               263
	#define DRAY_KEY_DOWN               264
	#define DRAY_KEY_UP                 265
	#define DRAY_KEY_PAGE_UP            266
	#define DRAY_KEY_PAGE_DOWN          267
	#define DRAY_KEY_HOME               268
	#define DRAY_KEY_END                269
	#define DRAY_KEY_CAPS_LOCK          280
	#define DRAY_KEY_SCROLL_LOCK        281
	#define DRAY_KEY_NUM_LOCK           282
	#define DRAY_KEY_PRINT_SCREEN       283
	#define DRAY_KEY_PAUSE              284
	#define DRAY_KEY_F1                 290
	#define DRAY_KEY_F2                 291
	#define DRAY_KEY_F3                 292
	#define DRAY_KEY_F4                 293
	#define DRAY_KEY_F5                 294
	#define DRAY_KEY_F6                 295
	#define DRAY_KEY_F7                 296
	#define DRAY_KEY_F8                 297
	#define DRAY_KEY_F9                 298
	#define DRAY_KEY_F10                299
	#define DRAY_KEY_F11                300
	#define DRAY_KEY_F12                301
	#define DRAY_KEY_F13                302
	#define DRAY_KEY_F14                303
	#define DRAY_KEY_F15                304
	#define DRAY_KEY_F16                305
	#define DRAY_KEY_F17                306
	#define DRAY_KEY_F18                307
	#define DRAY_KEY_F19                308
	#define DRAY_KEY_F20                309
	#define DRAY_KEY_F21                310
	#define DRAY_KEY_F22                311
	#define DRAY_KEY_F23                312
	#define DRAY_KEY_F24                313
	#define DRAY_KEY_F25                314
	#define DRAY_KEY_KP_0               320
	#define DRAY_KEY_KP_1               321
	#define DRAY_KEY_KP_2               322
	#define DRAY_KEY_KP_3               323
	#define DRAY_KEY_KP_4               324
	#define DRAY_KEY_KP_5               325
	#define DRAY_KEY_KP_6               326
	#define DRAY_KEY_KP_7               327
	#define DRAY_KEY_KP_8               328
	#define DRAY_KEY_KP_9               329
	#define DRAY_KEY_KP_DECIMAL         330
	#define DRAY_KEY_KP_DIVIDE          331
	#define DRAY_KEY_KP_MULTIPLY        332
	#define DRAY_KEY_KP_SUBTRACT        333
	#define DRAY_KEY_KP_ADD             334
	#define DRAY_KEY_KP_ENTER           335
	#define DRAY_KEY_KP_EQUAL           336
	#define DRAY_KEY_LEFT_SHIFT         340
	#define DRAY_KEY_LEFT_CONTROL       341
	#define DRAY_KEY_LEFT_ALT           342
	#define DRAY_KEY_LEFT_SUPER         343
	#define DRAY_KEY_RIGHT_SHIFT        344
	#define DRAY_KEY_RIGHT_CONTROL      345
	#define DRAY_KEY_RIGHT_ALT          346
	#define DRAY_KEY_RIGHT_SUPER        347
	#define DRAY_KEY_MENU               348
#endif